# HolmiumOS Limine Boot Configuration

# Limine'in otomatik boot etmeden önce bekleyeceği süre.
timeout: 0

/HolmiumOS
    # Limine boot protocol
    protocol: limine

    # Cosmos kernel image
    path: boot():/boot/HolmiumOS.elf